### ISSUE TITLE
Issue with Edge Lines Not Showing Between Items

### ISSUE THREAD

**Issue by DaikiFujiwara22** [ThatOpen/engine_components#143]
### Describe the bug 📝

```
this.renderer.postproduction.enabled = true;
const postproduction = renderer.postproduction;
postproduction.customEffects.outlineEnabled = true;
postproduction.customEffects.opacity = 1;
```

I tried to display edge lines using postproduction, and while the edge lines are showing, the edge lines between items are not displaying. Other postProduction effects are being applied.

In ifc.js, this issue didn't occur."
```
ifcViewerAPI.edges.createFromSubset(data.modelID, subset, mat);
ifcViewerAPI.edges.toggle(data.modelID, true);
```
![image (2)](https://github.com/IFCjs/components/assets/112066769/f85135fb-417c-44b5-9fd0-86a4642c5014)

![キャプチャ](https://github.com/IFCjs/components/assets/112066769/ee31bd62-26c9-475a-af11-88e617aed5e5)

### System Info 💻

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
    Memory: 8.30 GB / 15.71 GB
  Binaries:

    Node: 18.15.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.5.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.3570.0), Chromium (118.0.2088.46)
    Internet Explorer: 11.0.19041.3570
```

### Used Package Manager 📦

npm

### Validations ✅

- [X] Read the [docs](https://platform.thatopen.com/documentation).
- [X] Check that there isn't [already an issue](https://github.com/IFCjs/components/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a IFC.js components issue and not a framework-specific issue. For example, if it's a THREE.js related bug, it should likely be reported to [mrdoob/threejs](https://github.com/mrdoob/three.js) instead.
- [X] Check that this is a concrete bug. For Q&A join our [Community](https://people.thatopen.com/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by agviegas** [comment]
Hi @DaikiFujiwara22! I assume you are talking about the lines shown in the image below, right? The reason why this happens is that the postproduction effect draws the lines in real-time based on the faces of the geometry. The problem arises when 2 faces are coplanar because they are interpreted as the same face.

The reason why we are doing it this way instead of the previous approach is that this consumes zero memory, while the old `edges` strategy doubled the amount of memory (and draw calls) used, which of course was not a very scalable strategy.

I can try to improve the effect so that it improves for coplanar faces. Is there any chance I can have access to that model to see if I can make it work for it? Thanks in advance!

![image](https://github.com/IFCjs/components/assets/56475338/94ea8854-76e1-48ab-bcef-916ccd61ca46)

**Comment by DaikiFujiwara22** [comment]
Hi.
Thank you for your response.
The issue is that the following lines are not displayed.
![image3](https://github.com/IFCjs/components/assets/112066769/d9e2d4d3-1e01-4a8f-8137-4b0a8ac8d3f6)
I want to display the edge lines, but they are not appearing.
Is it not possible to display edge lines even when the faces are coplanar?
Below is the IFC file where the issue is occurring.
[IFC.zip](https://github.com/IFCjs/components/files/13262785/IFC.zip)

**Comment by agviegas** [comment]
I'll take a look. It's definitely not possible to solve this automatically because the GPU doesn't know what's in front of what (and thus the z fighting). An easy solution would be to make sure that the faces are not coplanar, but I know that this is not ideal or possible in many cases. I'll see if there's a fix that allows you to determine what's in front of what.

**Comment by agviegas** [comment]
I checked this and looks like the current implementation of the postproduction is not able to detect the difference between coplanar surfaces. This would be solved if that slab had actual holes to avoid overlap with the darker elements, or if the darker elements were bumping out just a bit. Closing this!
