### ISSUE TITLE
[Feat]: dot bim Import and export

### ISSUE THREAD

**Issue by Isaina** [ThatOpen/engine_components#296]
### What is your idea?

As ifc simple version can you support dotbim as import and export and import dotbim and export as ifc or import ifc and export as dotbim https://dotbim.net/ , needed in online usdz to ifc conversion workflow

**Comment by HoyosJuan** [comment]
Hi @Isaina!

According to the official [dotBIM repository](https://github.com/paireks/dotbim?tab=readme-ov-file), there is already:

* Converters between dotBIM and IFC (also viceversa).
* A dotBIM viewer in ThreeJS.

All our geometry is displayed in ThreeJS, so you can use the meshes generated by the dotBIM viewer (surely they have a parser) and display them in components; alternatively, you can use one of the dotBIM to IFC conversion tools in order to bring it into components. 

To be honest, at the time being is very unlikely we're going to add internal support for dotBIM files (merely because, as Tom said, we're focused on IFC). The good news is there are options to intergrate them together! So, it's just a matter of taking a look at their repo.

**Comment by Isaina** [comment]
There is a component to import dotBIm to three js so with clay can you make export so we can have online simple tool for that three.je to ifc Sent using the mobile mail appOn 05.03.2024. at 16:04, Juan Hoyos wrote:
                
            
            
                
                    From: "Juan Hoyos" ***@***.***>Date: 5 March 2024To: "ThatOpen/engine_components" ***@***.***>Cc: "Isaina" ***@***.***>,"Mention" ***@***.***>Subject: Re: [ThatOpen/engine_components] [Feat]: dot bim Import and export (Issue #296)
                
                
Closed #296 as not planned.
