### ISSUE TITLE
Clipping planes on certain elements in the scene

### ISSUE THREAD

**Issue by Adeniyi-Bella** [ThatOpen/engine_components#297]
### Description 📝

Extend the SimpleClipper class to enable a user to add clipping planes on certain elements in the scene but not directly on all elements. Currently, the position of the clipping planes is directly on the selected object but the clipping plane affects all objects in the scene. It would be nice to not have all the object in the scene been clipped when a user is using the clipping planes functionality.

### Suggested solution 💡

One way to solve the problem is to add clipping planes only to the elements that are necessary to be clipped. But it looks like the clipping planes have also been set on the renderer which makes it a global clipping plane. The solution here would be to ensure a clipping plane is not set on the renderer by default. A user can then decide to either set it on the renderer or on certain elements.

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [X] Check that there isn't [already an issue](https://github.com/IFCjs/components/issues) that requests the same feature to avoid creating a duplicate.

**Comment by agviegas** [comment]
Hey @Adeniyi-Bella! Right now we are trying to keep the scope of the library under control, because we are a small team and more code means more maintainance. The problem with using local clipping planes is that they won't work with postproduction. That said, you can use our [Clipper code](https://github.com/ThatOpen/engine_components/tree/main/packages/core/src/core/Clipper) as a reference and implement your own clipping component for your use case. If you need help with that, let us know! We'll be happy to guide you. Cheers!
