### ISSUE TITLE
New features for the project

### ISSUE THREAD

**Issue by JeanPaulLazaroQuispe** [ThatOpen/engine_components#391]
### Description 📝

I have a question about some features and would like to know if they are already available or if there are plans for their implementation. These are the ideas I would like to implement:

- Processing of the point cloud obtained from the DRON with the extension (.las).

- 3D model viewer (Sketchup)

- 3D model viewer (.IFC - Civil 3D)

- 3D model viewer (.DWG)

- 3D model viewer .IFC (Revit)

- Identification of incompatibilities, design optimization (3D navigation and parameter visualization, Integration).

- Project information model using BIM/GIS models (rendering).

- BIM Toolbar

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [X] Check that there isn't [already an issue](https://github.com/ThatOpen/engine_components/issues) that requests the same feature to avoid creating a duplicate.

**Comment by agviegas** [comment]
Hi @JeanPaulLazaroQuispe! Right now we are trying to keep the scope of the library under control. The reason is that the more code we add, the more code we need to maintain/improve over time. We are a small team yet, so choosing what we don't do for now (even if it's valuable) is even more important than choosing what we do. For us, it's better to have a small, powerful and up-to-date library than a massive library with many broken parts because we don't have time to fix them. So:

- There are libraries out there that can process and work with this kind of data.
- We already read and write IFC files, both for buildings and for roads.
- DWG is a proprietary format. What you need to open / edit it is not code, but a bank account.
- .rvt is a proprietary format. What you need to open / edit it is not code, but a bank account.
- These features can be easily built on top of our libraries. We are not adding them to the library for the reasons mentioned above.
- Idem as previous point.
- This is already provided by our UI [libraries](https://docs.thatopen.com/api/).

I hope this helps. Happy to answer any other questions you have. Cheers!
