### ISSUE TITLE
Make FragmentsGroup accessible

### ISSUE THREAD

**Issue by GlitchedCode** [ThatOpen/engine_components#411]
### Description 📝

I am currently working on a BIM application with typescript, and in an attempt to organize a codebase that will make use of most of the features provided by this project, i need to split code that will work on the loaded fragments and write functions that accept them. Loading a model gives me a FragmentsGroup object, but the class for this object is not exported publicly.

### Suggested solution 💡

Make FragmentsGroup a publicly accessible class for module users. IMO it should be by principle, since the user works directly with this object.

### Alternative ⛕

I'm working around this by using @ts-ignore, but it's not elegant at all to use it everywhere i need to reference the FragmentsGroup type.

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [X] Check that there isn't [already an issue](https://github.com/ThatOpen/engine_components/issues) that requests the same feature to avoid creating a duplicate.

**Comment by agviegas** [comment]
Hey, `FragmentsGroup` is exported by the `@thatopen/fragments` library, so you can import them like this:

```ts
import {FragmentsGroup} from @thatopen/fragments;
```

The library `@thatopen/fragments` is a peer dependency of this repo, so you probably already have it in your project. This should solve the issue you describe, but feel free to reopen this issue otherwise!
