### ISSUE TITLE
Highlighter ignores the culled fragment map entries 

### ISSUE THREAD

**Issue by SrujanPonnur1** [ThatOpen/engine_components#435]
### Describe the bug 📝

I am streaming an ifc file and trying to highlight nodes from the relationTree (where each entry would have a list of express ID's), but the highlight ignores highlighting the fragments that are culled from the scene. 

### Steps to reproduce 🔢

1. Use IFCStreamer to use any ifc file
2. Open RelationsTree tool, try to select any RelationsTree table entry (which contains children)
3. Check the Highlighters Selection Mapping

### System Info 💻

```shell
System:
    OS: Linux 6.5 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
    Memory: 6.18 GB / 15.30 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 19.9.0 - /usr/bin/node
    npm: 9.6.3 - /usr/bin/npm
  Browsers:
    Chrome: 124.0.6367.118
```

### Used Package Manager 📦

npm

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [X] Check that there isn't [already an issue](https://github.com/ThatOpen/engine_components/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a repository issue and not a framework-specific issue. For example, if it's a THREE.js related bug, it should likely be reported to [mrdoob/threejs](https://github.com/mrdoob/three.js) instead.
- [X] Check that this is a concrete bug. For Q&A join our [Community](https://people.thatopen.com/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by agviegas** [comment]
Hey, this is already fixed from `@thatopen/components-front@2.1.14`. 

Before reading the answer, keep in mind that the goal of streaming is to only load the geometries that the user sees. If you are building an app where the user highlights all items at all times, you will hit performance issues for bigger models and more modest machines, simply because that's the computational cost of loading that amount of geometry at the same time. This doesn't mean it won't work, but it's something to keep in mind.

I'm using the [streaming tutorial](https://docs.thatopen.com/Tutorials/Components/Front/IfcStreamer) code as starting point. There are 2 possible use cases:

## Case 1

You want to highlight, stream the highlighted elements and show them to the user. For example: show the user all the furnishing elements of a project. This can now be done like this:

```ts
  const model = await loader.load(geometryData, true, propertiesData);
  console.log(model);

  const highlighter = components.get(OBCF.Highlighter);
  const classifier = components.get(OBC.Classifier);
  classifier.byEntity(model);

  const furnitures = classifier.find({ entities: ["IFCFURNISHINGELEMENT"] });
  highlighter.add("example", new THREE.Color("red"));
  highlighter.config.world = world;

  window.addEventListener("keydown", async (event) => {
    if (event.code === "KeyP") {
      const furnituresIDs = Object.keys(furnitures);
      await loader.setStatic(furnituresIDs, true, false);
      await highlighter.highlightByID("example", furnitures, false, true);
    }
  });
}
```

When using `setStatic`, you are forcing the given items to be streamed. They will be kept in memory until the model is disposed or until they are removed from the static using `false` as the second `setStatic` parameter. The third parameter of `setStatic` determines whether the culler should be applied to these elements or not. I'm using `false` to ensure the elements are kept visible. When you are done highlighting the items, **remember to set them static to false** or the geometry will be kept in memory.  The result:

https://github.com/user-attachments/assets/631d0809-f98b-47e2-b04e-e27f78fa284a

## Case 2

You want to highlight the currently streamed elements, and highlight the ones that get streamed as they are discovered. For example: apply a red filter to all the furnishing elements of a project, but don't necesarily show them. This can now be done like this:

```ts
  const model = await loader.load(geometryData, true, propertiesData);
  console.log(model);

  const highlighter = components.get(OBCF.Highlighter);
  const classifier = components.get(OBC.Classifier);
  classifier.byEntity(model);

  const furnitures = classifier.find({ entities: ["IFCFURNISHINGELEMENT"] });
  highlighter.add("example", new THREE.Color("red"));
  highlighter.config.world = world;

  window.addEventListener("keydown", async (event) => {
    if (event.code === "KeyP") {
      await highlighter.highlightByID("example", furnitures, false, true);
    }
  });

  loader.onFragmentsLoaded.add((frags) => {
    highlighter.updateFragments(frags);
  });
}
```

As you see, in this case the highlighting style is applied to fragments only when they are streamed. This is the result:

https://github.com/user-attachments/assets/f0fd367a-2382-4f93-8b2b-83de8198d522

I hope this helps. Let me know how it goes!

**Comment by MadsHolten** [comment]
This is awesome, thanks. I am aware about the performance issues, but it will not be a problem with the particular case where I do for instance only want to load the furnishing elements. That's quite a common case for me. I might also want to load columns from model A and windows from model B together. In this case I would probably also build the JSON config on the fly so the streamer would never try to request anything but the elements in scope.

I will work on the implementation and give you a heads up if I discover something unexpected. Thanks a million for the swift response, that's much appreciated!

**Comment by MadsHolten** [comment]
Works pretty well now, I would say! This is an example of how I use it for spatial decomposition of the model 🤩


https://github.com/user-attachments/assets/6392834c-14f3-42dd-a43d-d66bc10ec977
