### ISSUE TITLE
Highlighter - Improving events

### ISSUE THREAD

**Issue by TobiasSeum** [ThatOpen/engine_components#460]
### Description 📝

I want to restore my custom highligher with your highlighter class. At the moment I am missing 2 features:

1: In the events 'onhighlight' and 'onclear' the information about the last change is missing (last selected elements?)
2: Suspend Events: I working with custom/ifc-file 'selection-groups'. That means I have stored a GlobalID which is represented in multiple Ifc-Elements/ExpressIds. When I am selecting a child of this group, my highlighter needs to check, if there are more elements to highlight. Now I want to use the function 'highlightById' without triggering the events.

### Suggested solution 💡

1: eventargs with list of last selection
2: new parameter (triggerEvents) or global functions: suspendEvents() and resumeEvents()

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [X] Check that there isn't [already an issue](https://github.com/ThatOpen/engine_components/issues) that requests the same feature to avoid creating a duplicate.

**Comment by agviegas** [comment]
Fixed from `@thatopen/components@2.4.0-alpha.3` and `@thatopen/components-front@2.4.0-alpha.4`:
11-SE-4720_PCR_PRY_VAR_MIB_IstramIFC4x3.ifc

- The highlighter now has an `eventManager` property that allow to turn off / on and reset all events.
- The highlighter now has an `onBeforeHighlight` event that returns the current selection before altering it with the new highlight operation. We did it like this because we didn't want a breaking change.

Let us know how it goes!
