### ISSUE TITLE
some IFC mesh elements not being properly processed with ifcLoader

### ISSUE THREAD

**Issue by yafimski** [ThatOpen/engine_components#468]
### Describe the bug 📝

I am loading a local .ifc file which represents a minimal HVAC example. 
It has a total of 56 elements in Revit. 
I export this from Revit 2024 with the IFC template of **IFC 2x3 Coordination View 2.0**.

![Screenshot 2024-08-11 143516](https://github.com/user-attachments/assets/7db20916-792c-43cd-9816-9bf6ca7279a3)

I expect the loaded model.children array to contain 56 mesh elements.
It has 48.

When loaded, the model populates the `world.scene.three` but boundingBoxer bboxes do not show up on some of the meshes.
![Screenshot 2024-08-11 143244](https://github.com/user-attachments/assets/de998b45-07f8-4172-83bb-4b8089419f3b)

Possible issue is that the library is not properly parsing 8 meshes of the 56.

### Steps to reproduce 🔢

Load the attached .ifc file (attached as .txt, change extension to .ifc):

[HVAC_Minimal.txt](https://github.com/user-attachments/files/16580754/HVAC_Minimal.txt)

Then use below code to load the model and display meshes, bounding boxes, and `model.children` array length:
```

const fragmentsManager = components.get(OBC.FragmentsManager);
const fragmentIfcLoader = components.get(OBC.IfcLoader);
await fragmentIfcLoader.setup();

fragmentIfcLoader.settings.webIfc.COORDINATE_TO_ORIGIN = true;

async function loadSpecific(url: string) {
  const file = await fetch(url);
  const data = await file.arrayBuffer();
  const buffer = new Uint8Array(data);
  const model = await fragmentIfcLoader.load(buffer);
  model.name = url.split("/").pop() || "";

  world.scene.three.add(model);

  if (model.children) {
    console.log(model.children.length);
    for (const child of model.children) {
      child.matrix = child.modelViewMatrix;
      child.updateMatrix();

      boundingBoxer.addMesh(child as Mesh);
      const bbox = boundingBoxer.getMesh();
      boundingBoxer.reset();
      const bboxHelper = new THREE.BoxHelper(bbox, "red");
      world.scene.three.add(bboxHelper);
    }
  }
}
```

### System Info 💻

```shell
`"@thatopen/components": "^2.1.16"`
```

### Used Package Manager 📦

npm

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [X] Check that there isn't [already an issue](https://github.com/ThatOpen/engine_components/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a repository issue and not a framework-specific issue. For example, if it's a THREE.js related bug, it should likely be reported to [mrdoob/threejs](https://github.com/mrdoob/three.js) instead.
- [X] Check that this is a concrete bug. For Q&A join our [Community](https://people.thatopen.com/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by agviegas** [comment]
Hi @yafimski, the `model.children` doesn't work like you expect. Each children is a fragment, and each fragment is an [InstancedMesh](https://threejs.org/docs/#api/en/objects/InstancedMesh) that contains all the instances of the same unique geometry. 

Looking at your second screenshot, looks like all the geometries are being loaded correctly. If you provide us with the model and a minimal script where you use the bounding boxer and tell us which fragment bounding box is not being generated correctly, we'll check it out. Otherwise, I think everything is working as expected and maybe you are not using the bounding boxer the way it's supposed to.

Cheers!

**Comment by agviegas** [comment]
@yafimski fragments don't work the way you expect. Each fragment is an extended [InstancedMesh](https://threejs.org/docs/#api/en/objects/InstancedMesh) that contain the whole set of unique geometries for that model. A fragment can contain geometries from multiple meshes, and a mesh can be made of multiple fragments.

Now, having said that, it's true that the boundingboxer had a small bug to generate boxes for individual fragment meshes like you were trying to. It's solved from `@thatopen/components@2.1.26`. With that fix, using your same code, this is the result now. notice how bounding boxes enclose sets of unique geometries, because that's how fragments work.

![image](https://github.com/user-attachments/assets/71328dfe-7bdb-4f19-9b90-01330798b6e0)

**Comment by yafimski** [comment]
@agviegas 
Would you be so kind as to provide a minimal code example of how to generate the bboxes for ALL the meshes..?
It seems quite a convoluted pathway right now to explore exactly to how put humpty dumpty back together again from fragments and instancedmeshes, perhaps you already have some direct way to get the actual meshes? i.e. a fragments-to-real-meshes function?

**Comment by agviegas** [comment]
@yafimski Sure! Cool thing about fragments is that they make it easy to access the original meshes and work with them. To generate the bounding boxes of all the meshes, you can do the following:

```ts
async function loadIfc() {
  const file = await fetch(
    "https://thatopen.github.io/engine_components/resources/small.ifc",
  );
  const data = await file.arrayBuffer();
  const buffer = new Uint8Array(data);
  const model = await fragmentIfcLoader.load(buffer);
  model.name = "example";
  // world.scene.three.add(model);

  const bboxer = components.get(OBC.BoundingBoxer);
  for (const [id] of model.data) {
    const item = model.getFragmentMap([id]);
    bboxer.addFragmentIdMap(item);
    const mesh = bboxer.getMesh();
    if (
      mesh.position.x > Number.MAX_VALUE ||
      mesh.position.x < -Number.MAX_VALUE
    ) {
      // Some items might not have geometric representation
      mesh.geometry.dispose();
      continue;
    }
    bboxer.reset();
    world.scene.three.add(mesh);
    const bboxHelper = new THREE.BoxHelper(mesh, "red");
    world.scene.three.add(bboxHelper);
  }
}
```

Which results in this:


https://github.com/user-attachments/assets/fc2d812a-37d5-41af-be0e-6f0321d38d72

**Comment by yafimski** [comment]
@agviegas 
Thanks! That is very cool indeed :)
I'm not sure if it's exactly the same as the below or not:

`if (model.children) {
    for (const child of model.children) {
      child.matrix = child.modelViewMatrix;
      child.updateMatrix();

      boundingBoxer.addMesh(child as Mesh);
      const bbox = boundingBoxer.getMesh();
      boundingBoxer.reset();
      const bboxHelper = new THREE.BoxHelper(bbox, "red");
      world.scene.three.add(bboxHelper);
    }
  }`

but something more central to my goals is to get the actual mesh triangles, I'm working on a clash-detection algorithm and what eluded me, beyond the boundingboxes, were the meshes themselves, since bboxes alone aren't good enough when it comes to AEC clash-detection.

It might be computationally intensive to just re-create real meshes from the instancedMeshes one by one and kind of reconstruct them.. and I'm not sure how practical that is, but how would you go about doing precise clash detection here? I would like to build that solution.

**Comment by agviegas** [comment]
@yafimski you probably don't want to recreate the Meshes as THREE.js meshes because that will dramatically increase the draw calls in your app, making it impossible to use even with modest BIM models. We tried that in the very beginning. That's the reason we created fragments. Feel free to try it out, but we've been there and it doesn't work.

My suggestion for you would be to make the clash detection with the geometries, and then once you detect a clash between 2 geometries, find out to which mesh that geometry belongs (which can be easily done with fragments). 

I'm not sure if this is your plan, but if your plan is to make a each-against-each clash detection, it's probably going to be very, very slow. If, like me, you are not familiar with computational geometry, I suggest you check out [Garrett's work](https://github.com/gkjohnson/three-mesh-bvh), which might help you make something efficient.

**Comment by yafimski** [comment]
@agviegas Thanks! 
Yeah I've been exploring his work and using Raycasting to try and somehow bypass some of the computation. It's showing promise I'm trying to check now if it scales.

The benefit of fragments is the loading time, for sure, but if they are zero'ed out in terms of position then I'm not sure I understand what you mean by "make the clash detection with the geometries", to get proper locations for the meshes I had to re-create all the positions/indices (since the indices are reset with InstancedMesh).
Can you elaborate..?

**Comment by agviegas** [comment]
No, the benefit of fragments is not the loading time. The fast loading time is because the geometry inside fragments is already converted to triangles. Using normal meshes would have the same speed.

The benefit of framgents is the performance. If you have a chair made of 2 geometries (the structure and the cushion), and you have a file with 1000 chairs:

- 1 mesh per chair: you get 1 draw call per mesh per material. 2000 draw calls. You wouldn't be able to move this on most computers, the lag would be terrible.
- fragments: 1 draw call per geometry, so only 2 draw calls. You would be able to move this easily even on phones.

If you are curious, try to create a single THREE.js mesh for each BIM mesh and you'll see what happens.

Now, imagine you perform a clash detection on those 1000 chairs. If you use fragments, you could get the following:

- cushion 678 clashes with structure 157.
- cushion 392 clashes with cushion 182.
- structure 191 clashes with structure 109.
- etc.

So once you have that, you only need to find out to which chair each geometry belongs, and you have the list of clashes for meshes. Fragments have methods to get the mesh ID from the geometry instance.

**Comment by yafimski** [comment]
Hmm... I generally get what you're saying but you say that if I use fragments I can get that cushion 678 clashes with structure 157, but when I tried it since they are both InstancedMesh their positions and geometry/indices are at the origin, so unless I transform them to their original positions using the instanceMatrix, they will clash for sure because they are on 0,0,0 despite the actual mesh in the IFC not clashing.. I hope I'm explaining correctly..

But in any case I'll try to explore what you say.

**Comment by agviegas** [comment]
If garret's code doesn't support instanced meshes, you can ask him, he's really nice and very helpful.

**Comment by yafimski** [comment]
Yep I've been exploring his code for a while. I'll dive into meshIDs again and make sure I didn't miss anything but definitely later will contact him, seems like he would know infinitely more than me about it ;)

Thanks!
