### ISSUE TITLE
Change material for entire model

### ISSUE THREAD

**Issue by tymokvo** [ThatOpen/engine_components#487]
Is there an idiomatic way to change the material for an entire model?

I have tried:

```typescript
model.items.forEach((itm) => { itm.mesh.material = [new three.MeshBasicMaterial({ color: "#fff", opacity: 0.5 })] })
```

but obviously, this is quite slow for an IFC with many elements.

My use case is for loading multiple models into a scene and being able to selectively set their opacity.

**Comment by agviegas** [comment]
@tymokvo all the items of the same BIM model can be in 2 groups: transparent and opaque. All the items of the same group share the same material for memory saving's sake. 

So if you pick any opaque item, or any transparent item, and change its material properties (like opacity and transparency), all the items of the same group will be affected. Of course, you can create a material per mesh, but that's going to be inefficient. Not because of our library, but because of three.js works.

If you want to make all the model transparent except for some items, I would do it like this:
- pick any opaque material of the model and set its properties transparent=true, opacity=0.5.
- create a [clone](https://docs.thatopen.com/api/@thatopen/fragments/classes/FragmentsGroup#clonegroup) of the items you want to set as opaque. You can clone a subset of the model.
- add a new material to the cloned items.
