### ISSUE TITLE
Configuring fragment generation categories per model

### ISSUE THREAD

**Issue by tymokvo** [ThatOpen/engine_components#496]
I see that it's possible to set both `includedCategories` and `excludedCategories` on the `IfcLoader` to limit fragment generation to subsets of an IFC file via the `settings`.

Is there a way to do this per-model? 

My use case is that I'm loading two models:
- consultant model
  - very small, elements could be any IFC category, unknown what to filter ahead of time
- arch model
  - very large, I know a priori that I only need walls, doors, and spaces

**Comment by aida-artepref** [comment]
Hi @tymokvo!

Currently, the IfcLoader settings for includedCategories and excludedCategories are applied globally, meaning they affect all models loaded through the instance of IfcLoader. Unfortunately, there isn't built-in support for configuring these categories on a per-model basis directly through IfcLoader.

However, there are a couple of potential workarounds that might help:
    -Separate Instances of IfcLoader: You could create a new instance of IfcLoader for each model, applying different settings to each one. This approach allows you to specify unique includedCategories and excludedCategories for each model but may increase memory usage if you’re handling multiple models simultaneously.
    -Custom Filtering After Loading: Another option is to load all elements initially and then apply custom filtering logic based on ExpressID or IFC type after loading each model. You can use the getProperties() function to retrieve and filter out the elements that don’t match your desired categories for each model.

**Comment by aida-artepref** [comment]
Example of creating two instances of ifcLoader
```javascript
import { IfcLoader } from 'web-ifc-three';

// Three.js scene where the models will be added
const scene = new THREE.Scene();
const renderer = new THREE.WebGLRenderer();
const camera = new THREE.PerspectiveCamera(75, window.innerWidth / window.innerHeight, 0.1, 1000);

// Configuration of each model
const consultantModelSettings = {
    includedCategories: ['IfcWall', 'IfcDoor'], // For example, only walls and doors
};

const archModelSettings = {
    excludedCategories: ['IfcFurniture'], // For example, exclude furniture
};

// Create an instance of IfcLoader for each model

const consultantModelLoader = new IfcLoader();
const archModelLoader = new IfcLoader();

// Assign the configurations to each instance
consultantModelLoader.ifcManager.applySettings(consultantModelSettings);
archModelLoader.ifcManager.applySettings(archModelSettings);

// Function to load and add models to the scene
async function loadModels() {
    const consultantModel = await consultantModelLoader.loadAsync('path/to/consultantModel.ifc');
    scene.add(consultantModel);

    const archModel = await archModelLoader.loadAsync('path/to/archModel.ifc');
    scene.add(archModel);

    renderer.setSize(window.innerWidth, window.innerHeight);
    document.body.appendChild(renderer.domElement);
    camera.position.z = 10;
    animate();
}


function animate() {
    requestAnimationFrame(animate);
    renderer.render(scene, camera);
}

loadModels().catch(error => console.error(error));

```

**Comment by tymokvo** [comment]
Thank you for the detailed response! I had been avoiding creating multiple instances of the `IfcLoader` as the memory usage is already very high. Do you know if one approach is better than the other from that perspective?

I had ended up using your "custom filtering" option. Basically loading the models generically and then wrapping the `IfcApi` to only get elements with a certain type ID, then matching on STEP ID.

**Comment by aida-artepref** [comment]
Thank you for your feedback! I understand the memory concerns with multiple IfcLoader instances. Here’s a bit more context on memory usage for each approach:

Memory Considerations
Multiple IfcLoader Instances: Each IfcLoader instance indeed consumes its own set of resources, as it initializes separate data structures to manage the model. This approach allows for clear separation of settings per model but can increase memory usage, especially with large or multiple models.

Custom Filtering (Single IfcLoader Instance): Your current approach (loading all models with one IfcLoader instance and filtering elements with a custom wrapper around IfcAPI) is often more memory-efficient. Since you’re only maintaining one set of IfcLoader data structures, memory usage should generally be lower, though filtering might add a bit of processing overhead. This option also has the advantage of giving you finer control over what gets processed, which can be useful for large models.

I hope this helps clarify the trade-offs.

**Comment by tymokvo** [comment]
It does! I'll go ahead and close since there's a couple options  laid out here to accomplish the goal. But it might be worth adding an example to demonstrate those tradeoffs.
