### ISSUE TITLE
Loading Big IFC

### ISSUE THREAD

**Issue by ManuzXo** [ThatOpen/engine_components#503]
Hi, I noticed that if I load a large IFC, like 90 MB of IFC, I go at 10 fps, the performance drops and with 20 MB or less of IFC data, I remain stable at 60 fps, any solution?

**Comment by nicoarellano** [comment]
Have you tried using the [ifcStreamer](https://docs.thatopen.com/Tutorials/Components/Front/IfcStreamer)? Instead of loading the full model, you stream the parts that you require. This works for geometry and properties.  It gets rid of loading times and it is much performant.  
I use is with 500MB+ IFCs and it works great.
Let me know if you need guidance setting it up.

**Comment by ManuzXo** [comment]
Hi, these days I’ve been using the culler, and it works well, especially to avoid a drop in FPS. However, if I’m not mistaken, the streamer must have saved the .json files somewhere, which adds an extra step in the design phase that I don’t want to deal with.

I want the user to load the IFC and see it in one step. At the moment, the culler seems okay, although I would prefer to have the model fragments always visible rather than loading some fragments and not others (lazy loading)

**Comment by agviegas** [comment]
@ManuzXo it's not possible to load an IFC fast and display it efficiently because IFC was never designed for visualization speed. That's why we created fragments (and streaming): to be able to open huge amounts of geometries fast. Glad that the culler does the job for you. If you find a better solution, feel free to propose it! Closing this for now

Thanks @nicoarellano for taking care :)
