### ISSUE TITLE
import Formats

### ISSUE THREAD

**Issue by ThatMetaverseArchitect** [ThatOpen/engine_components#75]
### Description 📝

More formats to import especially for the 2D PDF or 2D DWG Plan import, as well as .ifczip format.
![2023-05-04 12_16_03_importFormats](https://github.com/IFCjs/components/assets/137836321/f38eca83-3d55-4091-967f-8820b237d163)

### Validations ✅

- [X] Read the [docs](https://ifcjs.github.io/info/docs/Introduction).
- [X] Check that there isn't [already an issue](https://github.com/IFCjs/components/issues) that requests the same feature to avoid creating a duplicate.

**Comment by sabromeo1961** [comment]
We should also consider importing DXF files Standard exchange file for CAD Drawings.

If importing PDF should consider converting to SVG so that lines and vertices can be selected

**Comment by agviegas** [comment]
Hey, now we are trying to keep the library as small as possible, because with the current team we can't afford to maintain a big codebase. I would say:
- For IFCzip, just unzip it before opening it with the library. This can be easily done with libraries [like this](https://github.com/greggman/unzipit).
- For PDF, you can load it in Three.js using external libraries. Other people [has done it before](https://discourse.threejs.org/t/document-or-pdf-viewer-in-threejs-environment/18729).
- DWG is a proprietary format and can't be opened without the according license / sdk, which you can pay Autodesk for.

**Comment by ThatMetaverseArchitect** [comment]
@agviegas 
thanks for the response. I have posted a year ago and did not get the notification of your answer.
I understand the taskforce is big.. I will refer to your references for the future developments.
