### ISSUE TITLE
wishlist from umdaschgroup

### ISSUE THREAD

**Issue by ThatMetaverseArchitect** [ThatOpen/engine_components#76]
### Description 📝

1)	BIG IFC models to upload and view it as fast as possible
2)	Import and Export IFC2x3 CV2.0 and IFC4.3 (*it would be nice to show the [structural analytical view](https://forums.autodesk.com/t5/revit-structure-forum/structural-analysis-view-mvd/td-p/10444594), including .ifczip format
3)	What we really need is to display the geometrical and non-geometrical information accurately in web IFC viewer.
![20220208_Autodesk_Support_BaseQuantities_Gross_and_NetVolume_Error_02](https://github.com/IFCjs/components/assets/137836321/457d2a10-6da7-403e-8cec-c8c431f59eef)

a.	Autodesk BIM360 or ACC viewer fails to open the geometry of IFC (see. Attached images- model geometry error), we would like to avoid this problem
![20210519_Image01_IFC_Model_GeoemtryError_in_ACC](https://github.com/IFCjs/components/assets/137836321/fa404225-9489-48eb-8d5b-67440fdaaea6)

b.	When the origin of model is far over 100 km away, we found that Autodesk BIM360 or ACC viewer fails to display the object accurate.. (see. Attached images- model geometry error),
![20210521_Image03_IFC_Model_Geometry_Error_in_ACC](https://github.com/IFCjs/components/assets/137836321/60edbbf7-664c-417f-a6cf-8ecfd1126b3e)

c.	Orthographic & perspective view mode, as well as overriding shaded colour options
d.	IfcPresentationLayerAssignment information in the model tree
e.	3D viewCube and zoom options
f.	Selected item graphic display (Highlight selected item and have the option to show unselected items in transparent or wireframed view)
g.	Overlay PDF drawings

4)	Create Parameter and PropertySet
a.	If we can create the addtional IfcParameter and PropertySet would be great. For example, we need Quanity parameters and values, however, we get sometimes without the Quantity parameter and values from the clients. We use simplebim or IfcOpenShell to add the Quantity parameters and values at the moment… It would be great if Tooeen can have the same features.
5)	Federating the Ifc Models.
a.	We would like to keep the different IfcBuilding within one IfcSite when we federate the models (see. Attached example of simplebim and solibri/ IfcModelStructure)
![20210908_IfcModelStructure_Solibri](https://github.com/IFCjs/components/assets/137836321/6d8c6805-6de1-475c-8ff6-0c063b96b431)
![20210908_IfcModelStructure_simplebim](https://github.com/IFCjs/components/assets/137836321/d87df9eb-7128-48ef-afde-645e8033b3a0)

b.	When we federate the models, we would like to have a good federated building storey structure
c.	Custom model tree – to show both federated Ifc Model structure and individual Ifc model structure
6)	Merging model
a.	We have to merge different Ifc files and export as a one model from time to time. At the moment, we use simplebim for it. Can we have this feature?
7)	CDE feature
a.	I like the idea to connect with SharePoint for example. Then we could really use Tooeen as CDE (Common Data Environment) to upload not only IFC models

8)	Modifying Element Property
a.	Re-assign IfcBuildingStorey
b.	If we can automize the reassigning IfcBuildingStorey based on the element elevation would be great.
c.	Re-assign IfcClass. For example, we get many IfcBuildingElementProxy from our clients. It would be nice if we can re-assign the Ifc Entity and Type according to the buildingSMART classificaiton
d.	Modifying the existing parameter values

9)	Clear Documentation to find out the information of the codes.

### Validations ✅

- [X] Read the [docs](https://ifcjs.github.io/info/docs/Introduction).
- [X] Check that there isn't [already an issue](https://github.com/IFCjs/components/issues) that requests the same feature to avoid creating a duplicate.

**Comment by agviegas** [comment]
Working on it @ThatMetaverseArchitect! Do we have access to all these models?

**Comment by agviegas** [comment]
1. Big IFCs can now be loaded fast with [streaming](https://docs.thatopen.com/Tutorials/Components/Front/IfcStreamer).
2. All versions of IFC are now supported. For IFCzip, you can easily unzip it using a library [like this](https://github.com/greggman/unzipit) and then opening it with our library.
3. Here are all the responses:

- 3.a. I think most (if not all) the geometry issues for your models have been already solved. Otherwise, you can open specific issues in the [core library](https://github.com/ThatOpen/engine_web-ifc) and we'll address the remaining ones. 
- 3.b. We can also open all your models, even the ones that are far away from the origin.
- 3.c. We now support [orthographic and perspective view](https://docs.thatopen.com/Tutorials/Components/Core/OrthoPerspectiveCamera), as well as a [shaded option](https://docs.thatopen.com/api/@thatopen/components-front/classes/PostproductionRenderer).
- 3.d. The model tree provided by the library can be customized, or you can build your own with the existing API.
- 3.e. We now have a [view cube](https://docs.thatopen.com/api/@thatopen/ui-obc/classes/ViewCube) in the UI library.
- 3.f. The [highlighter](https://docs.thatopen.com/api/@thatopen/components-front/classes/Highlighter) allows for customization, and the model graphics [can be customized](https://docs.thatopen.com/Tutorials/Components/Core/Classifier) as you see fit.
- 3.g. To overlay PDF drawings you can just use specific libraries to load them in the Three.js scene. You can [see this](https://discourse.threejs.org/t/document-or-pdf-viewer-in-threejs-environment/18729) as an example.

4. We can already edit the existing properties and create new ones. 
5. Here are all the responses:

- 5.a. Federation of multiple models is already supported.
- 5.b. and 5.c. The current API allows the structure can be customized to your needs.

6. Our current API already supports this!
7. This is also already supported.
8. IFC property edits are already supported by our API without limits, so all these points are possible with our libraries!
9. Done! You can check it [here](https://docs.thatopen.com/intro).
